# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160924_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
