# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161012_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, default='#4CAF50', max_length=255, null=True),
        ),
    ]
